Repository somosphi/js-logger, pull requests merged in 2020-03, with the labels that each got.

#4 Cloudflare header support for express
  CHANGELOG.md
  package-lock.json
  package.json
  src/packages/ExpressLogger.ts
Labels: enhancement

#5 Release 1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement

#8 Redact
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/index.ts
  src/logger.ts
  src/packages/AxiosLogger.ts
  src/packages/ExpressLogger.ts
  src/packages/Redact.ts
  src/packages/RequestLogger.ts
  src/packages/__tests__/AxiosLogger.unit.test.ts
  src/packages/__tests__/ExpressLogger.unit.test.ts
  src/packages/__tests__/Redact.unit.test.ts
  src/packages/__tests__/RequestLogger.unit.test.ts
  types/index.d.ts
Labels: enhancement

#9 omit routes regexp
  CHANGELOG.md
  package-lock.json
  package.json
  src/packages/ExpressLogger.ts
  src/packages/Redact.ts
  src/packages/__tests__/ExpressLogger.unit.test.ts
Labels: bug, enhancement

#10 fix redact and express buffer
  CHANGELOG.md
  src/packages/ExpressLogger.ts
  src/packages/Redact.ts
Labels: bug
